---
- name: Inject IP Addr in AD/DNS
  hosts: all
  gather_facts: false
  tasks:
    - name: Compute Short Hostname for debugging
      debug:
        msg: "{{ inventory_hostname.split('.')[0] }}"
    - name:  Add DNS A record
      win_dns_record:
        name: "{{ inventory_hostname.split('.')[0] }}"
        type: A
        zone: "{{ inventory_hostname.split('.')[1:4] | join('.') }}"
        value: "{{ os_ipv4_addr }}"
        state: present
      delegate_to: "{{ ad_host }}"
      connection: winrm
      port: 5986
...
